accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('<str:username>-<int:user_id>/profile', views.UserProfileView.as_view(), name='user_profile'),
]

onlineshop/urls.py
from django.urls import path, include
from . import views
app_name = 'onlineshop'
urlpatterns = [

    path('', views.display_products, name="product_list"),
    path('<slug:category_slug>/', views.display_products, name="product_category"),
]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onlineshop.urls')),
    path('accounts/register/', views.UserRegistration.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User # Import django user model
from django.utils.translation import gettext_lazy as _  # This is to get a better reading text.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12, blank=True)
    location = models.CharField(max_length=30, blank=True)
    date_of_birth = models.DateField(_('Birth date'), blank=True, null=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.") # Help the user enter date.

onlineshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
 
    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'
 
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('onlineshop:product_category', args=[self.slug])
 
 
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
 
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)
 
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_details', args=[self.id, self.slug])

accounts/forms.py
from registration.forms import RegistrationForm
from registration.forms import RegistrationFormUniqueEmail
from django.contrib.auth.models import User
from django import forms

class ProfileForm(RegistrationFormUniqueEmail):
    pass

class UserRegistrationForm(ProfileForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')
    
        
        
 

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from registration.backends.default.views import RegistrationView
from .forms import ProfileForm, UserRegistrationForm
from . models import Profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomePageView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['title'] = 'Home'
        return context


class UserRegistration(RegistrationView):
    form_class = UserRegistrationForm
    def register(self, form_class):
        new_user = super(UserRegistration, self).register(form_class)
        Profile.objects.create(user=new_user)
        return new_user

@method_decorator(login_required, name='dispatch')
class UserProfileView(TemplateView):
    template_name = 'profile/user_profile.html'
    

        
   

onlineshop/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404
from . models import Category, Product


def display_products(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
 
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'onlineshop/product/product_list.html', context)

def product_details(request, product_id, slug):
    product = get_object_or_404(Product, id=product_id, slug=slug)
    return render(request, 'onlineshop/product/product_details.html', {'product':product})

accounts/templates/includes/form.html
{% load widget_tweaks %}

{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

accounts/templates/includes/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

accounts/templates/includes/navbar.html
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a class="navbar-brand" href="{% url 'onlineshop:product_list' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
       <li class="nav-item">
        <a class="navbar- nav-link" href="{% url 'onlineshop:product_list' %}">All Products</a>
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link" href="#">Login as {{user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_logout' %}">logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'registration_register' %}">Signup</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% if messages %}
    <div class="container">
      <div class="row">
        <div class="col-sm-7 mx-auto mt-1">
          {% include 'includes/messages.html' %}
        </div>
      </div>
    </div>
    {% endif %}

accounts/templates/includes/pagination.html
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.number > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">First</span>
        </li>
      {% endif %}

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}

      {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

accounts/templates/profile/user_profile.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <h1>User Profile</h1>
    </div>
</div>
{% endblock %}

onlineshop/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css" integrity="sha256-RdH19s+RN0bEXdaXsajztxnALYs/Z43H/Cdm1U4ar24=" crossorigin="anonymous" />
    {% block styles %} {% endblock %}
    <title>{% block title %} {% endblock %}|Great Guys Online Shop</title>
  </head>
  <body>
    {% block content %}
    
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.js" integrity="sha256-wk7QMTzYE7BJvko9BsywPzRmKzhCtIQKTuN6/B9sRmw=" crossorigin="anonymous"></script>
  </body>
</html>

onlineshop/templates/onlineshop/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css" />
{% endblock %}
{% block title %} {% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-9 mt-5">
            <div class="row">
                {% for product in products %}
                <div class="col-md-4 mt-3">
                <div class="card shadow-sm bg-white rounded">
                  <img class="card-img-top pr-2 pl-2" {% if product.image %} src="{{product.image.url}}" {% else %} src="{% static 'image/default.png' %}" {% endif %} alt="Card image cap">
                  <div class="card-body">
                    <a href="#"><h5 class="card-title text-center">{{product.name}}</h5></a>
                    <p class="card-text text-center">${{product.price}}</p>
                  </div>
                </div>
                </div>
                {% endfor %}
            </div>
            
        </div>
        <div class="col-12 col-md-3 mt-5">
        <h4 class="text-center">Categories</h4>
        <ul class="list-unstyled text-center">
             <li {% if not category %} class="active"{% endif %}><a href="{% url 'onlineshop:product_list' %}">All</a></li>
             
             {% for category in categories %}
              <li {% if category.slug == category.slug %} class="active"{% endif %}>
                  <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
              </li>
            {% endfor %}
        </ul>
            
        </div>
    </div>
</div>

{% endblock %}